services:
  bookstack:
    image: lscr.io/linuxserver/bookstack:${BOOKSTACK_VERSION}
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - APP_URL=${APP_URL}:${APP_HOST_PORT}
      - APP_KEY=base64:0q4VP5Fzy3LFKuzbvoLyOe/Tb9WU0xmFOtb4/T2Gnso=
      - DB_HOST=bookstack_db
      - DB_PORT=${DB_CONTAINER_PORT}
      - DB_DATABASE=${MYSQL_DATABASE}
      - DB_USERNAME=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./bookstack_data:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
  
  bookstack_db:
    image: lscr.io/linuxserver/mariadb:${MARIADB_VERSION}
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./bookstack_dbdata:/config
    restart: unless-stopped